SELECT
    i.ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM ITEM_INFO i
WHERE not i.ITEM_ID in (
    SELECT 
        PARENT_ITEM_ID
    FROM ITEM_TREE 
    WHERE PARENT_ITEM_ID is not NULL
    GROUP BY PARENT_ITEM_ID
)
ORDER BY i.ITEM_ID desc