SELECT 
    d.ROUTE,
    CONCAT(ROUND(sum(D_BETWEEN_DIST),1), 'km') as TOTAL_DISTANCE,
    CONCAT(ROUND(avg(D_BETWEEN_DIST),2), 'km') as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE d
GROUP BY d.ROUTE
ORDER BY sum(D_BETWEEN_DIST) desc