SELECT
    i.ID,
    n.FISH_NAME,
    i.LENGTH
FROM FISH_INFO i
INNER JOIN FISH_NAME_INFO n on i.FISH_TYPE = n.FISH_TYPE
WHERE (n.FISH_TYPE,i.LENGTH) in (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY i.ID;